version: "3.4"
services:

    # PHP service
    app:
        build: ./docker/php
        container_name: cal-api-php-app
        working_dir: /var/www/
        volumes:
            - ./:/var/www
            - ./profiler:/tmp/xdebug
            - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
        environment:
            XDEBUG_CONFIG: client_host=127.0.0.1
            PHP_IDE_CONFIG: serverName=calc-api
            XDEBUG_SESSION: calc-api
        networks:
            - cal-api-app-network

    # Nginx service
    nginx:
        image: nginx:alpine
        container_name: cal-api-php-nginx
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - cal-api-app-network

networks:
    cal-api-app-network:
        driver: bridge
